CREATE DATABASE hacker_news;

USE hacker_news;

CREATE TABLE Stories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    storyId VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    url TEXT NOT NULL,
    date DATE NOT NULL,
    time DATETIME NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
